# The Default Profile
[profile.default]
solc_version = '0.8.15'
auto_detect_solc = false
optimizer_runs = 1_000
eth_rpc_url = 'https://rpc.ankr.com/eth'
fork_block_number = 15460423

[profile.fuzz]
runs = 1_000

# Extreme Fuzzing CI Profile :P
[profile.fuzz.ci]
runs = 100_000