# The Default Profile
[profile.default]
solc_version = '0.8.17'
auto_detect_solc = false
optimizer_runs = 1_000

[profile.ci_mainnet]
eth_rpc_url = 'https://rpc.ankr.com/eth'
fork_block_number = 16448815

[profile.ci_arbitrum]
eth_rpc_url = 'https://rpc.ankr.com/arbitrum'
fork_block_number = 54308474
